# Generated by Django 2.1 on 2019-12-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('checkInDate', models.DateField(auto_now_add=True, null=True)),
                ('checkOutDate', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('SW', 'SWIMMING'), ('SN', 'SNOOKER'), ('BAR', 'BAR')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('visitorCount', models.IntegerField(blank=True, default=0, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='HotelFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Feature')),
                ('h_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Hotel')),
            ],
            options={
                'verbose_name': 'HotelFeature',
                'verbose_name_plural': 'HotelFeatures',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('checkInDate', models.DateField(blank=True, null=True)),
                ('checkOutDate', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('DROPPED', 'DROPPED')], max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='h_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Status'),
        ),
    ]
